[package]
name = "paragram"
version = "0.1.0"
authors = ["T4toun3 <oettam32@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unidecode = "0.3.0"
itertools = "0.10.0"
rayon = "1.5.0"